### ISSUE TITLE
Ссылка на получение токена не актуальная

### ISSUE THREAD

**Issue by drno-reg** [maksim77/tinkoff_exporter#7]
https://tinkoffcreditsystems.github.io/invest-openapi/auth/#_2

<img width="715" alt="изображение" src="https://user-images.githubusercontent.com/19163425/151227569-d7fbf56e-a46e-4b9e-87be-afe417e30beb.png">

**Comment by maksim77** [comment]
Спасибо!
Поправил.

P.S. Используйте аккуратно. Я очень давно не следил за их API и логикой работы. Может что уже и сломалось.
